name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: coming-soon
  BUCKET_NAME: coming-soon-website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          version: '356.0.0'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r dist gs://${{ env.BUCKET_NAME }}

